# Pre-commit checks run on STAGED files by default — so legacy files won't block you
# If you run `pre-commit run -a`, we exclude the known-bad backup file.
exclude: |
  (?x)^(
    birdeye_ws_backup\.py
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]        # auto-fix
      - id: ruff-format      # ruff formatter (safe; after black it's a no-op for py)

  # Optional: mypy on changed files (kept fast/safe)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive