line-length = 100
target-version = "py312"
respect-gitignore = true
force-exclude = true

extend-exclude = [
  "attic",
  "**/*_backup.py",
  "**/*_bak.py",
  ".venv",
  "build",
  "dist",
  "node_modules",
  "__pycache__",
]

[lint]
# Start small: only Pyflakes (F) + import sorting (I)
select = ["F","I"]

# Common temporary ignores; adjust later
ignore = [
  "E501",    # line length (we already format to 100)
]

[format]
quote-style = "double"

[lint.per-file-ignores]
# app.py references optional helpers that aren’t always present; also has an intentional re-def.
"app.py" = ["F821", "F811"]

# Tests import handlers just to assert they import; mark unused-imports ok there.
"tests/**/*.py" = ["F401"]

# Worker optionally imports a polling bot that may not be used in this mode.
"polling_worker.py" = ["F401"]
"**/test_*.py" = ["F401"]
