[project]
name = "mork-fetch-bot"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "base58>=2.1.1",
    "black==24.8.0",
    "coverage>=7.6.1",
    "cryptography>=45.0.6",
    "flask>=3.1.1",
    "httpx>=0.25.2",
    "mypy==1.10.0",
    "openai>=1.99.9",
    "pre-commit>=3.7.1",
    "pynacl>=1.5.0",
    "pytest>=8.3.2",
    "python-telegram-bot>=22.3",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "ruff==0.5.7",
    "solana>=0.36.7",
    "solders>=0.26.0",
    "sqlalchemy>=2.0.42",
    "telegram>=0.0.1",
    "types-python-dateutil==2.9.0.20240316",
    "types-requests==2.32.0.20240712",
    "unidiff>=0.7.5",
    "websocket>=0.2.1",
    "websockets>=15.0.1",
]

[project.optional-dependencies]
dev = [
    "black==24.8.0",
    "ruff==0.5.7", 
    "mypy==1.10.0",
    "pytest==8.3.2",
    "coverage==7.6.1",
    "pre-commit==3.7.1",
    "types-requests==2.32.0.20240712",
    "types-python-dateutil==2.9.0.20240316"
]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
# We'll lint only changed files in CI, so no giant excludes needed yet.
# Add ignores as we tighten later.

[tool.coverage.run]
branch = true
source = ["."]
omit = [
  "attic/*",
  "tests/*",
  "scripts/*",
]

[tool.coverage.report]
show_missing = true
skip_covered = false
