[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = '''
(^|/)(birdeye_ws_backup\\.py|.*_backup\\.py|\\.venv/|dist/|build/|\\.git/)
'''

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I","UP","B","SIM","PL","RUF"]
ignore = ["E501"]
extend-exclude = ["birdeye_ws_backup.py", "*_backup.py", ".venv", "dist", "build"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = true
exclude = '(^|/)(birdeye_ws_backup\\.py|.*_backup\\.py|\\.venv/|dist/|build/)'
