[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
# We'll lint only changed files in CI, so no giant excludes needed yet.
# Add ignores as we tighten later.
