[project]
name = "mork-fetch-bot"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "base58>=2.1.1",
    "coverage>=7.6.1",
    "cryptography>=45.0.6",
    "flask>=3.1.1",
    "httpx>=0.25.2",
    "openai>=1.99.9",
    "pre-commit>=3.7.1",
    "pynacl>=1.5.0",
    "pytest>=8.3.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "solana>=0.36.7",
    "solders>=0.26.0",
    "sqlalchemy>=2.0.42",
    "telegram>=0.0.1",
    "unidiff>=0.7.5",
    "websocket>=0.2.1",
]

[project.optional-dependencies]
dev = [
    "black==24.8.0",
    "ruff==0.5.6", 
    "mypy==1.10.0",
    "pytest==8.3.2",
    "coverage==7.6.1",
    "pre-commit==3.7.1",
    "types-requests==2.32.0.20240712"
]

[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = "(^|/)(attic/|.*_backup\\.py)"

[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = ["attic", "*_backup.py", ".venv", "venv"]

[tool.ruff.lint]
select = ["E","F","I","UP","B"]
ignore = [
    "E501",    # let black handle line-length
    "E722",    # bare except (common in production telegram bots)
    "E402",    # module import not at top (needed for sys.path modifications)
    "PLR2004", # magic values (status codes are self-documenting)
    "PLR0912", # too many branches (complex bot logic)
    "PLR0915", # too many statements (complex bot methods)
    "SIM105",  # contextlib.suppress (explicit try/except is clearer)
    "SIM115",  # context manager (file locking requires manual control)
    "B904",    # raise from err (not critical for telegram bots)
    "B018",    # useless expression (pattern for checking var existence)
    "F841",    # unused variable (development/debugging artifacts)
    "F401",    # unused import (conditional imports for testing)
    "UP038",   # isinstance syntax (backwards compatibility)
    "F821",    # undefined name (missing functions - will be addressed separately)
    "F811",    # redefinition (duplicate function definitions)
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = true
exclude = '(^|/)(attic/|.*_backup\\.py)'
