[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "anthropic>=0.61.0",
    "asyncio>=4.0.0",
    "base58>=2.1.1",
    "beautifulsoup4>=4.13.4",
    "cryptography>=45.0.6",
    "email-validator>=2.2.0",
    "filelock>=3.19.1",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "httpx[http2]>=0.25.2",
    "numpy>=2.3.2",
    "openai>=1.99.9",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "psutil>=7.0.0",
    "psycopg2-binary>=2.9.10",
    "pynacl>=1.5.0",
    "python-dotenv>=1.1.1",
    "python-telegram-bot==20.7",
    "pyyaml>=6.0.2",
    "qrcode>=8.2",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "selenium>=4.34.2",
    "solana>=0.36.7",
    "solders>=0.26.0",
    "sqlalchemy>=2.0.42",
    "telegram>=0.0.1",
    "trafilatura>=2.0.0",
    "unidiff>=0.7.5",
    "websocket>=0.2.1",
    "websocket-client==1.8.0",
    "websockets>=15.0.1",
    "werkzeug>=3.1.3",
]

[tool.black]
line-length = 100
target-version = ["py310"]
exclude = "(\.venv|build|dist|.*/generated/|.*/__pycache__/|tests/fixtures/)"

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [".venv", "build", "dist", "tests/fixtures"]
select = ["E","F","I","UP","B","SIM","PL","RUF"]
ignore = [
  "E501",  # handled by black
  "SIM117" # sometimes explicit is clearer
]

[tool.ruff.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = true
exclude = "tests/fixtures"
