[project]
name = "mork-fetch-testbot"
version = "1.0.0"
description = "Test version of Mork F.E.T.C.H Bot"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "anthropic>=0.61.0",
    "asyncio>=4.0.0",
    "base58>=2.1.1",
    "beautifulsoup4>=4.13.4",
    "cryptography>=45.0.6",
    "email-validator>=2.2.0",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "numpy>=2.3.2",
    "openai>=1.99.1",
    "pandas>=2.3.1",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "selenium>=4.34.2",
    "solana>=0.36.7",
    "solders>=0.26.0",
    "sqlalchemy>=2.0.42",
    "trafilatura>=2.0.0",
    "websocket-client>=1.8.0",
    "websockets>=15.0.1",
    "werkzeug>=3.1.3",
]
