[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["birdeye_ws_backup.py"]

[tool.ruff.lint]
select = ["F","E","W","B","I","UP","N","C4"]
ignore = ["E501"]  # line length handled by Black

[tool.ruff.lint.per-file-ignores]
"birdeye_ws_backup.py" = ["ALL"]