name: quality
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest
      - name: Run pre-commit (black/ruff/mypy)
        run: pre-commit run --all-files
      - name: Targeted watchlist tests (offline)
        env:
          PYTHONPATH: .
          FETCH_ENABLE_SCANNERS: "0"
          FEATURE_WS: "off"
        run: |
          python -m pytest -q tests/test_watchlist*.py tests/test_watch*.py
