name: Quality
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install tools
        run: |
          python -m pip install -U pip
          python -m pip install ruff==0.5.6 black==24.8.0 mypy==1.10.0
      - name: Black (check)
        run: python -m black --check . --extend-exclude '(^|/)(attic/|.*_backup\.py)'
      - name: Ruff
        run: python -m ruff check . --extend-exclude 'attic' --extend-exclude '*_backup.py'
      - name: Mypy
        run: python -m mypy . --exclude '(^|/)(attic/|.*_backup\.py)'