name: Quality
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install tools
        run: |
          python -m pip install -U pip
          python -m pip install black==24.8.0 ruff==0.5.6 mypy==1.10.0 pre-commit==3.7.1
      - name: Pre-commit (Black, Ruff, Mypy on changed files)
        run: |
          python -m pre_commit run --all-files