name: watchlist
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env:
          PYTHONPATH: '.'
        run: ./run_watchlist_tests.sh

  full:
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env:
          PYTHONPATH: '.'
          FETCH_ENABLE_SCANNERS: '1'
          FEATURE_WS: 'on'
          SOLSCAN_API_KEY: ${{ secrets.SOLSCAN_API_KEY }}
          BIRDEYE_API_KEY: ${{ secrets.BIRDEYE_API_KEY }}
        run: ./run_watchlist_tests.sh