name: watchlist-test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python3 -m pip install -r requirements.txt || true
      # Adjust STRICT/TEST_TIMEOUT as you like (STRICT=1 will fail on '?')
      - run: STRICT=1 TEST_TIMEOUT=8 python3 tests/test_watchlist.py