name: tests
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env: { TEST_TIMEOUT: '8' }
        run: |
          python3 tests/test_watchlist.py
          python3 tests/test_watchlist_edge.py
          python3 tests/test_watch_remove.py
          python3 tests/test_watchlist_scale.py

  scanners:
    if: ${{ secrets.ENABLE_SCANNERS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env:
          FETCH_ENABLE_SCANNERS: '1'
          FEATURE_WS: 'on'
          TEST_TIMEOUT: '12'
          SOLSCAN_API_KEY: ${{ secrets.SOLSCAN_API_KEY }}
          BIRDEYE_API_KEY: ${{ secrets.BIRDEYE_API_KEY }}
          WATCH_REMOVE_CMD: '/watch_remove'
        run: |
          python3 tests/test_watchlist.py
          python3 tests/test_watchlist_edge.py
          python3 tests/test_watch_remove.py
          python3 tests/test_watchlist_scale.py